[package]
name = "learning-rust"
version = "0.1.0"
authors = ["Kyle Rassweiler <dev@kylerassweiler.ca>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
